import Header from "@/components/Header/Header";
import "../normalize.css";
import "./globals.scss";
import { Chakra_Petch } from "next/font/google";
import Footer from "@/components/Footer/Footer";

const chakra = Chakra_Petch({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  style: ["normal"],
});

export const metadata = {
  title: "VRNas",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={chakra.className}>
        <div className="wrapper">
          <Header />
          <main>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
